/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ratcap.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const model = '../assets/ratcap.gltf'

export default function Model(props) {
  const { nodes, materials } = useGLTF(require(model))
  return (
    <group {...props} dispose={null}>
      <group position={[0.193, 0.305, -0.079]} rotation={[-0.015, 0, 0]} scale={[0.877, 0.503, 0.877]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Gold} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.White} />
      </group>
    </group>
  )
}

useGLTF.preload(model)
